### ISSUE TITLE
ValueError: arrays must all be same length

### ISSUE THREAD

**Issue by tianyichow** [gotec/git2net#7] opened 2020-01-13 08:20 UTC
**Describe the bug**
Hi, git2net is really cool! It helps a lot. 

Recently I use git2net to mine some repos and find a error.

**To Reproduce**

The repos  I work with are  `["996.ICU","ant-design","element","taro","Paddle","vue-cli","tidb","ant-design-pro","incubator-echarts","vue"]`.  An error occur in some repos when running  git2net.mine_git_repo(repo_dir, sqlite_db_file,no_of_processes=20). So part of the commits log in those repos cannot be mining by git2net.

__repos with problems:__

* ant-design = "https://github.com/ant-design/ant-design.git"
* taro = "https://github.com/NervJS/taro.git"
* Paddle= "https://github.com/PaddlePaddle/Paddle.git"
* incubator-echarts= "https://github.com/apache/incubator-echarts.git"
* vue = "https://github.com/vuejs/vue.git"

**error info**

![BUG](https://user-images.githubusercontent.com/42535236/72240344-d0e7ea80-361e-11ea-91a0-1e4a440b43d7.png)

![BUG2](https://user-images.githubusercontent.com/42535236/72240348-d2b1ae00-361e-11ea-830c-7f27f7149405.png)

**Comment by gotec** [comment] 2020-01-13 08:31
Hi Tianyi,

Thanks for reporting this bug, I'm glad you find git2net helpful.

From what I see it happens when parsing the blame. Do you have the hash of an example commit for which the error occurs? This would be incredibly helpful for debugging as I'll be very limited on time for the next 4 weeks.

Cheers,
Christoph

**Comment by tianyichow** [comment] 2020-01-13 10:52
Hi Christoph，
For example，in this repo:  vue = "https://github.com/vuejs/vue.git",
with the code below：
`commits = ['270b0ac021ee5bfff6b2ed1eacaf91a09f2a9d5e']
git2net.mine_git_repo(repo_dir, sqlite_db_file, commits=commits, no_of_processes=1)
`
This commit is an example for this kind of error. I hope this can be helpfull.
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-5dc946256414> in <module>
      1 commits = ['270b0ac021ee5bfff6b2ed1eacaf91a09f2a9d5e']
      2 
----> 3 git2net.mine_git_repo(repo_dir, sqlite_db_file, commits=commits, no_of_processes=1)

~/anaconda3/envs/tylab/lib/python3.6/site-packages/git2net/extraction.py in mine_git_repo(repo_string, sqlite_db_file, use_blocks, no_of_processes, chunksize, exclude, blame_C, max_modifications, timeout, commits)
   1546                              commits=u_commits, use_blocks=use_blocks,
   1547                              no_of_processes=no_of_processes, exclude=exclude,
-> 1548                              blame_C=blame_C, max_modifications=max_modifications, timeout=timeout)

~/anaconda3/envs/tylab/lib/python3.6/site-packages/git2net/extraction.py in _process_repo_serial(repo_string, sqlite_db_file, commits, use_blocks, no_of_processes, exclude, blame_C, max_modifications, timeout)
   1176                 'no_of_processes': no_of_processes, 'max_modifications': max_modifications,
   1177                 'timeout': timeout}
-> 1178         result = _process_commit(args)
   1179 
   1180         if not result['commit'].empty:

~/anaconda3/envs/tylab/lib/python3.6/site-packages/git2net/extraction.py in _process_commit(args)
   1075                                                         use_blocks=args['use_blocks'],
   1076                                                         blame_C=args['blame_C'],
-> 1077                                                         no_of_processes=args['no_of_processes']),
   1078                                                 ignore_index=True, sort=True)
   1079                     except GitCommandError:

~/anaconda3/envs/tylab/lib/python3.6/site-packages/git2net/extraction.py in _extract_edits_merge(git_repo, commit, modification_info, use_blocks, blame_C, no_of_processes)
    773                                         modification_info['old_path'])
    774             if len(parent_blame2) > 0:
--> 775                 parent_blame2 = _parse_porcelain_blame(parent_blame2).rename(
    776                                 columns={'line_content': 'pre_line_content',
    777                                         'line_number': 'pre_line_number'})

~/anaconda3/envs/tylab/lib/python3.6/site-packages/git2net/extraction.py in _parse_porcelain_blame(blame)
    312             elif entries[0] == 'filename':
    313                 filename = entries[1]
--> 314     blame_info = pd.DataFrame(l)
    315     return blame_info
    316 

~/anaconda3/envs/tylab/lib/python3.6/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    409             )
    410         elif isinstance(data, dict):
--> 411             mgr = init_dict(data, index, columns, dtype=dtype)
    412         elif isinstance(data, ma.MaskedArray):
    413             import numpy.ma.mrecords as mrecords

~/anaconda3/envs/tylab/lib/python3.6/site-packages/pandas/core/internals/construction.py in init_dict(data, index, columns, dtype)
    255             arr if not is_datetime64tz_dtype(arr) else arr.copy() for arr in arrays
    256         ]
--> 257     return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
    258 
    259 

~/anaconda3/envs/tylab/lib/python3.6/site-packages/pandas/core/internals/construction.py in arrays_to_mgr(arrays, arr_names, index, columns, dtype)
     75     # figure out the index, if necessary
     76     if index is None:
---> 77         index = extract_index(arrays)
     78     else:
     79         index = ensure_index(index)

~/anaconda3/envs/tylab/lib/python3.6/site-packages/pandas/core/internals/construction.py in extract_index(data)
    366             lengths = list(set(raw_lengths))
    367             if len(lengths) > 1:
--> 368                 raise ValueError("arrays must all be same length")
    369 
    370             if have_dicts:

ValueError: arrays must all be same length
```

**Comment by gotec** [comment] 2020-01-15 09:22
Hi Tianyi,

yesterday I spent some time trying to replicate the issue. Unfortunately I was not able to. Mining the "vue" repository with `git2net.mine_git_repo('vue', 'vue.db')` as well as trying the commit you mentioned worked flawlessly on my system (git2net 1.1.7 and Ubuntu 18.04 with US locale).

Which system are you working on?
Best,
Christoph

**Comment by tianyichow** [comment] 2020-01-15 09:31
Hi Christoph,
My system is CentOS Linux release 7.7.1908 (Core) and git2net 1.1.7.  

But when I run
`commits = ['270b0ac021ee5bfff6b2ed1eacaf91a09f2a9d5e'] 
git2net.mine_git_repo(repo_dir, sqlite_db_file, commits=commits, no_of_processes=1)` on MacOS, no error occurs. 🤯

Best,
Tianyi

**Comment by gotec** [comment] 2020-01-15 09:59
Yes, this is exactly what I experienced. So I have to assume this is an issue with CentOS...

For now I will add a warning in the Readme but I wouldn't know how to debug this without installing CentOS myself. In case you find a solution a pull request would be highly welcome.

**Comment by tianyichow** [comment] 2020-01-15 10:06
Ok, I will try it out. Thanks for your help. 😄

**Comment by gotec** [comment] 2020-01-15 10:07
I have updated the Readme. I will leave this issue open as a reminder to set up a system running CentOS at some point.

Cheers,
Christoph

**Comment by gotec** [comment] 2020-02-20 17:44
Hi Tianyi,

I have just set up a VM with CentOS 8 and was not able to reproduce the issue. Again 'vue' runs fine for me. If I have time I will try with CentOS 7.7.1908 as now I'm very curious about what could cause this.
Are you using a specific locale or is your system set to English?

Cheers,
Christoph

**Comment by gotec** [comment] 2020-02-26 18:29
Good news! I was able to replicate the issue in CentOS 7.7 and, after a long search, I think I also found the source of the problem.

By default, CentOS 7.7 uses an older version of git (< 2) which was released more than 5 years ago and is no longer maintained. This version has different behaviour and output of git-blame as well as other commands. I have now (git2net version 1.2.2) made sure that git2net only runs for git versions >=2 to avoid the errors you were seeing.
To properly use git2net with CentOS 7.7 you need to update your git version. For me, [these instructions on stackoverflow](https://stackoverflow.com/questions/21820715/how-to-install-latest-version-of-git-on-centos-7-x-6-x) worked great.

Based on this, I will close this issue.

I hope this helps you!

Best,
Christoph

**Closed as completed by gotec** 2020-02-26 18:29 UTC
